version: '3'
services:
  proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
#    networks:
#      - laravel

  my-laravel:
    build: .
    image: custom-laravel
    volumes:
      - ./laravel:/root/laravel
#    networks:
#      - laravel
    command: ["php", "artisan", "serve", "--host", "0.0.0.0", "--port", "81"]

#networks:
#  laravel:
#    external: true
