version: '3'
services:
  proxy:
    container_name: m-proxy
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - laravel
      
  my-laravel:
    container_name: m-laravel
    build: .
    image: custom-laravel
    volumes:
      - ./laravel-project:/root/laravel-project
    networks:
      - laravel
    #command: ["/bin/bash", "entrypoint"]

networks:
  laravel:
    external: true
